{
 "title": "DashBoard-Mlops",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_status_restarts_total{\n    namespace=\"default\",\n    pod=~\"mlops-savings-app.*\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD Network (MB/s)(IN)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_network_receive_bytes_total{\n    namespace=\"default\",\n    pod=~\"mlops-savings-app.*\"\n  }[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"default\",\n    pod=~\"mlops-savings-app.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{\n  namespace=\"default\",\n  pod=~\"mlops-savings-app.*\"\n}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  kube_pod_status_phase{\n    namespace=\"default\",\n    pod=~\"mlops-savings-app.*\",\n    phase=\"Running\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD Network (MB/s) (OUT)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_network_transmit_bytes_total{\n    namespace=\"default\",\n    pod=~\"mlops-savings-app.*\"\n  }[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{container!=\"\", image!=\"\"}[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)MiB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{\n    namespace=\"default\",\n    pod=~\"mlops-savings-app.*\",\n    container!=\"\",\n    image!=\"\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Error Packets",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_network_receive_errors_total{\n    namespace=\"default\",\n    pod=~\"mlops-savings-app.*\"\n  }[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}